version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: sbds
       MYSQL_USER: user
       MYSQL_PASSWORD: password

   sbds:
     depends_on:
       - db
     build: ..
     ports:
       - "8080:80"
     restart: always
     environment:
       DATABASE_URL: mysql+mysqldb://user:password@db/sbds?charset=utf8mb4
       STEEMD_HTTP_URL: https://api.steemit.com
       SBDS_LOG_LEVEL: DEBUG

volumes:
    db_data:
