version: '2'
services:
  web:
    image: sbdsimg
    env_file: .env
    ports:
     - "8080:8080"
    entrypoint:
      - dev-server
  db_block_loader:
    build: .
    image: sbdsimg
    env_file: .env
    entrypoint:
      - /usr/src/app/sbds/storages/db/scripts/populate.sh
  block_streamer:
    image: sbdsimg
    env_file: .env
