version: '3'

services:
   db:
    image: postgres:10.1-alpine
    #image: postgres:9.6.7-alpine
    restart: always
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: sbds
    ports:
       - "5432:5432"
volumes:
    db_data:
