version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo "Ignore CircleCI detected dependencies"
      - run: docker build -t steemit/sbds .